"""Add indoor and double columns to courts, remove features

Revision ID: 6d7ea99a4fb3
Revises: f664ba0abdd2
Create Date: 2025-11-11 20:36:13.949477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d7ea99a4fb3'
down_revision: Union[str, Sequence[str], None] = 'f664ba0abdd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courts', sa.Column('indoor', sa.Boolean(), nullable=True))
    op.add_column('courts', sa.Column('double', sa.Boolean(), nullable=True))
    op.drop_column('courts', 'features')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courts', sa.Column('features', sa.VARCHAR(), nullable=True))
    op.drop_column('courts', 'double')
    op.drop_column('courts', 'indoor')
    # ### end Alembic commands ###
