"""Add unique constraint to location slug

Revision ID: add_unique_slug_constraint
Revises: add_search_order_tables
Create Date: 2025-11-16 15:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "add_unique_slug_constraint"
down_revision = "add_search_order_tables"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_locations_slug", "locations", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_locations_slug", "locations", type_="unique")
    # ### end Alembic commands ###
