"""Add unique constraint to location slug

Revision ID: add_unique_slug_constraint
Revises: add_search_order_tables
Create Date: 2025-11-16 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_unique_slug_constraint'
down_revision = 'add_search_order_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite to add unique constraint
    with op.batch_alter_table('locations') as batch_op:
        batch_op.create_unique_constraint('uq_locations_slug', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations') as batch_op:
        batch_op.drop_constraint('uq_locations_slug', type_='unique')
    # ### end Alembic commands ###