"""Add timezone column to locations table

Revision ID: d9090b31251b
Revises: 1d63dcf5e3cd
Create Date: 2025-11-28 18:43:00.723670

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9090b31251b"
down_revision: Union[str, Sequence[str], None] = "1d63dcf5e3cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "locations",
        sa.Column(
            "timezone", sa.String(), nullable=True, server_default="Europe/Amsterdam"
        ),
    )
    # Update existing rows to have the default timezone
    op.execute(
        "UPDATE locations SET timezone = 'Europe/Amsterdam' WHERE timezone IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locations", "timezone")
    # ### end Alembic commands ###
