"""Add more fields to locations and courts

Revision ID: f664ba0abdd2
Revises: a714dd8e1ba1
Create Date: 2025-11-11 20:07:07.384611

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f664ba0abdd2"
down_revision: Union[str, Sequence[str], None] = "a714dd8e1ba1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courts", sa.Column("sport", sa.String(), nullable=True))
    op.add_column("courts", sa.Column("features", sa.String(), nullable=True))
    op.add_column("locations", sa.Column("tenant_id", sa.String(), nullable=True))
    op.add_column("locations", sa.Column("slug", sa.String(), nullable=True))
    op.add_column("locations", sa.Column("address", sa.String(), nullable=True))
    op.add_column("locations", sa.Column("opening_hours", sa.String(), nullable=True))
    op.add_column("locations", sa.Column("sport_ids", sa.String(), nullable=True))
    op.add_column(
        "locations", sa.Column("communications_language", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locations", "communications_language")
    op.drop_column("locations", "sport_ids")
    op.drop_column("locations", "opening_hours")
    op.drop_column("locations", "address")
    op.drop_column("locations", "slug")
    op.drop_column("locations", "tenant_id")
    op.drop_column("courts", "features")
    op.drop_column("courts", "sport")
    # ### end Alembic commands ###
